### ISSUE TITLE
About the performance on OpenQA

### ISSUE THREAD

**Issue by jinzhuoran** [AI21Labs/in-context-ralm#1]
Hi @oriram, I read your paper with great interest, and I would like to keep up with your work.
I'm curious if you have done experiments on OpenQA, because I tried GPT-J to answer questions with several evidences and it was difficult to get satisfactory answers.

**Comment by oriram** [comment]
Hey @jinzhuoran,
Thanks for your interest in our work!

We did experiments on OpenQA using LLaMA, they will be included in the next version of our paper (later this week).
Hopefully, we'll soon be able to release the code as well.
