### ISSUE TITLE
Can you please provide the implementation for training a predictive reranking model?

### ISSUE THREAD

**Issue by siyuanseever** [AI21Labs/in-context-ralm#2]
I only found information about zero-shot reranking and oracle experiments in the documentation, but there seems to be no configuration provided for training a reranking model. I would like to train a reranking model to compare its performance with the zero-shot approach.

**Comment by bulubulu-Li** [comment]
+1

**Comment by oriram** [comment]
Thanks for reaching out!
The repo currently doesn't support training a reranking model.
I'll be happy to assist in implementation if it's relevant.
