### ISSUE TITLE
TriviaQA settings

### ISSUE THREAD

**Issue by kerkathy** [AI21Labs/in-context-ralm#3]
Hi, 

Thank you for your excellent work and detailed analysis in the paper! 
It seems that the code in this repo only contains LM experiments but no Open Domain QA parts. 
However, I wish to reproduce the ODQA results. Therefore, I'm curious about the implementation details for TriviaQA dataset. 
I saw that in `prepare_retrieval_data.py`, we concatenated all text before sending them to the retriever to index them. 
I wonder for TriviaQA what did you put into the database? 
Is it `entity_pages`(the ones already marked relevant with questions) or the complete `evidence` folder? 
And could you kindly share how they're preprocessed before being fed into retriever? 
Thanks again!

**Comment by oriram** [comment]
Hey @kerkathy ,
Thanks for reaching out!

The repo does contain the code for reproducing QA experiments:
https://github.com/AI21Labs/in-context-ralm#question-answering-experiments

For TriviaQA, we simply used the question as the query to the retriever, similar to [DPR](https://arxiv.org/abs/2004.04906).
I hope it answers your question.

Thanks!

**Comment by kerkathy** [comment]
Thanks for your reply!
Ah, I see. I was curious about your retrieval corpora, which supposed should be `the Wikipedia corpus from Dec. 20, 2018` as mentioned in the paper. Then I supposed it's contained in the file after running the following code, right? If so, then I have no more questions, thanks!
```
wget https://dl.fbaipublicfiles.com/dpr/data/retriever_results/single/nq-test.json.gz
gzip -d ./nq-test.json.gz
```

**Comment by oriram** [comment]
This file only contains the results of running the DPR retriever on the questions of NQ over the wikipedia corpus (i.e., it does not contain the corpus itself).

**Comment by oriram** [comment]
Hi @kerkathy ,
We just added the dataset with retrieval results for TriviaQA as well - see in the README.
Best,
Ori

**Comment by kerkathy** [comment]
That's really nice of you! thanks!
