### ISSUE TITLE
TriviaQA dataset

### ISSUE THREAD

**Issue by jxjessieli** [AI21Labs/in-context-ralm#4]
Hi, thank you for your interesting and insightful work! I would like to reproduce your results on the TriviaQA dataset. Could you provide the TriviaQA dataset augmented by DPR or the script to obtain the retrieved documents? Thank you!

**Comment by oriram** [comment]
Hi @jxjessieli,
Thanks for reaching out and using our repo!
I added the TriviaQA dataset augmented by DPR to a public bucket on GS.
Can you try to install `gsutil` and run
```
gsutil cp gs://ai21-publishing-public-models/in-context-ralm/trivia-test-dpr-results.json PATH/TO/FILE.json
```
If that works for you, I'll add it to the README.
Best,
Ori

**Comment by jxjessieli** [comment]
Hi Ori,

Thank you for providing access to the augmented TriviaQA dataset. The script works smoothly for me. 
Could you please specify which version of the DPR retriever was used for both the NQ and TriviaQA datasets, as there are different versions, such as the nq-base and the multiset-base? Thank you very much!

Best,
Jiaxi

**Comment by oriram** [comment]
Sure:
- For NQ, we used the official DPR-NQ checkpoint released by Meta (i.e., `single-nq-base`)
- For TriviaQA, we used our own DPR-TriviaQA model, trained for a previous [paper](https://arxiv.org/abs/2112.07708) on the training set of TriviaQA (the dataset was released by Meta).
