### ISSUE TITLE
BM25 indexing and searching

### ISSUE THREAD

**Issue by hieudx149** [AI21Labs/in-context-ralm#5]
Hi there, i see in your code, in searching phrase, you use gpt2 tokenizer to tokenize the query. In indexing pharse, do you also use gpt2 tokenizer to process the corpus?

**Comment by oriram** [comment]
Hey @hieudx149,
Thanks for reaching out!

We don't use gpt2 tokenizer when indexing, we use the default tokenizer of `pyserini`.
