### ISSUE TITLE
LLAMA experiment

### ISSUE THREAD

**Issue by kerkathy** [AI21Labs/in-context-ralm#6]
Hi,

Thank you for adding the QA datasets last time!
Though I saw on README about how to run the QA experiment, I want to make sure if the script can be directly run by replacing `$MODEL_NAME` by LLAMA models on huggingface, like `meta-llama/Llama-2-7b`. Or some other api should be implemented? thanks!

**Comment by oriram** [comment]
I'm pretty sure it should work fine with LLaMA-2.
Just make sure that the version of `transformers` in `requirements.txt` is compatible (i.e., not too early).
Let me know if you have any problems :)

**Comment by kerkathy** [comment]
hello :)
I noticed that in the README of QA experiment we need to directly download the DPR retrieval result.
Could you also provide the code for performing this DPR retrieval from wiki corpus? thank you!

**Comment by oriram** [comment]
Hey @kerkathy,
The code for performing the retrieval can be found either in https://github.com/facebookresearch/DPR or https://github.com/oriram/spider.
Let me know if you need any help :)

**Comment by kerkathy** [comment]
Thank you. I get it! :)

**Comment by kerkathy** [comment]
hi, I'm sorry to bother you again
I've been using Pyserini to perform DPR retrieval. However the retrieval result only contains id without raw content. 
It seems that Faiss index (what DPR is using) doesn't save raw content.
Can you kindly share how you obtain the raw content back? Did you use a LuceneSearcher additionally, or simply save a dictionary file with id-text mapping for correspondence?

thank you!

**Comment by oriram** [comment]
Hey @kerkathy,
Please feel free to ask any question :)

We used the Wiki corpus from DPR, which you should be able to download from:  https://dl.fbaipublicfiles.com/dpr/wikipedia_split/psgs_w100.tsv.gz (or using their repo).

The IDs returned by Pyserini correspond to the IDs in this corpus.

Good luck!
Ori

**Comment by kerkathy** [comment]
Thank you! I'm able to fetch the content now:)
